dev:
  cmd: 
    - go build
    - go install
  srcs:
    - main.go
    - dev.yaml
  deps:
    - subtask1
    - subtask2

subtask1:
  cmd:
    - echo '***** task 1 ******'
  cache: true
  srcs:
    - main.go
    - dev.yaml


subtask2:
  cmd:
    - echo '***** task 2 ******'
  cache: true
  srcs:
    - main.go
    - dev.yaml
